import dicom
import sys
data = dicom.read_file(sys.argv[1])
x = list()
x.append(data.StudyID)
x.append(data.PatientsName)
x.append(data.PatientID)
x.append(data.SeriesNumber)
x.append(data.SeriesInstanceUID)
x.append('')
x.append('')
x.append(data.PatientPosition)
x.append(data.AcquisitionTime)
x.append('')
x.append('')
x.append('')
x.append('')
x.append(data.KVP)
x.append('')
x.append(data.InstitutionName)
x.append(data.Manufacturer + ' ' + data.ManufacturersModelName)
x.append(str(data.PixelSpacing[0]) + ' ' +
         str(data.PixelSpacing[1]) + ' ' + 
         str(data.SpacingBetweenSlices))
x.append('')
x.append(str(data.WindowWidth[0]) + ' ' + str(data.WindowWidth[0]))
x.append(data.SliceThickness)
x.append('')
x.append('')
x.append('')
x.append('')
for i in x:
  sys.stdout.write(str(i) + ',')
sys.stdout.write('\n')
